### ISSUE TITLE
Generating Step Definitions Overwites Previous Definitions

### ISSUE THREAD

**Issue by adamrodger** [specsolutions/deveroom-visualstudio#51]
**Version**: 1.4.2

**Steps**:

1. Create a new feature file and add a scenario with undefined steps, e.g.:
  ```
  Scenario: Add
    Given I have entered 5
    And I have entered 6
    When I press add
    Then the result should be 11
  ```
2. Use "Define Steps (Ctrl+B, D)" to generate the step definitions and press Create
3. Write a new scenario which uses a new step definition, e.g.:
  ```
  Scenario: Multiply
    Given I have entered 5
    And I have entered 6
    When I press multiply <---- this step definition is new
    Then the result should be 30
  ```
4. Use "Define Steps" again

**Expected**: A new step definition is generated and added to the existing step definitions file.

**Result**: The entire step definition file is overwritten and now only contains 1 step definition.

**Comment by adamrodger** [comment]
I believe the problem is here: https://github.com/specsolutions/deveroom-visualstudio/blob/c03e17590e7035485ee0b2727ab7fb3c8424ec31/Deveroom.VisualStudio/Editor/Commands/DefineStepsCommand.cs#L138-L153

This method doesn't check whether a file with the same name already exists, it just overwrites with a new file containing only the new steps definitions every time.

**Comment by gasparnagy** [comment]
It is fixed in a way that at least asks before overwrite. Later we can improve this to extend existing file...

**Comment by sanjayforonbe** [comment]
I am still facing above issue, just the confirmation is there now.
