### ISSUE TITLE
Support for Specflow 3.9.22

### ISSUE THREAD

**Issue by tlecomte** [specsolutions/deveroom-visualstudio#72]
Using Deveroom with a project using Specflow 3.9.22 fails with:

> System.TypeLoadException: 'Method 'LoadPlugin' in type 'TechTalk.SpecFlow.Plugins.RuntimePluginLoader_Patch' from assembly 'deveroom-specflow-v3, Version=1.0.0.0, Culture=neutral, PublicKeyToken=c392b06fa519a0e0' does not have an implementation.'

As far as I can tell, this comes from the following change, where `IRuntimePluginLoader.LoadPlugin` has changed to take one extra parameter:
https://github.com/SpecFlowOSS/SpecFlow/pull/2462

**Comment by tlecomte** [comment]
@gasparnagy Out of curiosity, what do you think of the idea of shipping the discovery command-line tool as part of the Specflow nuget itself? That would make the Deveroom extension less dependent on internal changes in Specflow. The "contract" would be the command-line arguments of that command, and the format of the json it returns.

**Comment by gasparnagy** [comment]
@tlecomte Yes, this is something we are considering with the SpecFlow team. Most probably the Rider extension could also use it then. There are some work on the IDE extensions right now and we will finalize the plan soon.

**Comment by gasparnagy** [comment]
This is fixed with v1.6.3

**Comment by tlecomte** [comment]
Hello @gasparnagy, the source for v1.6.3 does not show up in Github, maybe you forgot to push ?

**Comment by gasparnagy** [comment]
@tlecomte yes... done now.

**Comment by tlecomte** [comment]
Thanks @gasparnagy :smile:
